```{r label=packagesAndFunctions, include=FALSE}
library(dplyr)
library(tidyr)
library(rstan)
library(biomaRt)
library(parallel)
source("../src/StatisticalFunctions.R")
source("../src/GeneticFunctions.R")
```


```{r label=datareadin, include=FALSE}
data_folder = "../data"
# Gene-trait associations from GWAS and OMIM genetic evidence (current and Nelson)
gene_trait_association_table0 <- read.delim(paste0(data_folder, "/gene_trait_assoc.tsv"), stringsAsFactors = FALSE)
# Drug target-indication links with success (with my maps and maps standardized to n et al.).
target_indication_table <- read.delim(paste0(data_folder, "/target_indication.tsv"), stringsAsFactors = FALSE)
# trait - indication similarity
average_similarity <- read.delim(paste0(data_folder, "/indication_trait_similarity.tsv"), stringsAsFactors = FALSE, check.names = FALSE)
# gene properties, used in statistical models
gene_properties <- read.delim(paste0(data_folder,"/Target_Properties.tsv"), stringsAsFactors = FALSE)
# top mesh, used in statistical models
mesh_properties <- read.delim(paste0(data_folder,"/top_mesh.tsv"), stringsAsFactors = FALSE)
``` 

```{r label = RemoveXMHC, include=FALSE}
gene_trait_association_table <- filter(gene_trait_association_table0, !xMHCGene)
# target-indication was already filtered to remove these genes.
# gene-trait association not to allow option of xMHC success prediction
```

```{r label=DefiningDatasetForGenePropertyAnalysis, include=FALSE, cache=TRUE}
# Our statistical model only operates on target-indication pairs with known success or failure (not those currently active without
# known failures)
target_indication_table_known_status <- filter(target_indication_table, Inactive | lApprovedUS.EU)
```

```{r label=DefaultPriorParameterValues, include=FALSE, cache=TRUE}
sigmab=2
mualpha=-2.2
sigmaalpha=0.75

ncore = 4
```

```{r label=RunningStanGWAS, include=FALSE, cache=TRUE}
stan_gwas <- run_stan(target_indication_table = target_indication_table_known_status, association_table = gene_trait_association_table, MSH_similarity = average_similarity, top_mesh = mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(gwas = gwas_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/gwas.rds", cores = ncore)
```

```{r label=RunningStanOMIM, include=FALSE, cache=TRUE}
stan_omim <- run_stan(target_indication_table = target_indication_table_known_status, association_table = gene_trait_association_table, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(omim = OMIM_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/omim.rds", cores=ncore)
```

```{r label=RunningStanGWASDel, include=FALSE, cache=TRUE}
del_filter <- function(gene_trait_association_table) {
  filter(gene_trait_association_table, R2 >= 0.9, Deleterious %in% c("MODERATE", "HIGH"))
}

stan_del <- run_stan(target_indication_table = target_indication_table_known_status, association_table = gene_trait_association_table, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(del = del_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/del.rds", cores=ncore)
```

```{r label=RunningStanGWAS2013, include=FALSE, cache=TRUE}
new_associations <- filter(gene_trait_association_table, (Source== "GWAS:A" & first_added > as.Date("2013-05-21")) |
                           (Source == "OMIM" & first_added > as.Date("2013-10-03")))

stan_gwas_2013 <- run_stan(target_indication_table = target_indication_table_known_status, association_table = new_associations, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(gwas = gwas_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/gwas_new.rds", cores=ncore)
```

```{r label=RunningStanOMIM2013, include=FALSE, cache=TRUE}
stan_omim_2013 <- run_stan(target_indication_table = target_indication_table_known_status, association_table = new_associations, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(omim = OMIM_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/omim_new.rds", cores=ncore)
```

```{r label=RunningStanGWASDel2013, include=FALSE, cache=TRUE}
stan_del_2013 <- run_stan(target_indication_table = target_indication_table_known_status, association_table = new_associations, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(del = del_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/del_new.rds", cores=ncore)
```

```{r label=RunningStanBoth, include=FALSE, cache=TRUE}
stan_both <- run_stan(target_indication_table = target_indication_table_known_status, association_table = gene_trait_association_table, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = rep(2,2), filter_list=list(gwas=gwas_filter, omim=OMIM_filter), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/both.rds", cores=ncore)
```

```{r label=RunningStanAny, include=FALSE, cache=TRUE, eval=FALSE}
stan_any <- run_stan(target_indication_table = target_indication_table_known_status, association_table = gene_trait_association_table, MSH_similarity = average_similarity, top_mesh = mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(any = function(x) {x}), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/any.rds", cores = ncore)
```

```{r label=RunningStanAny2013, include=FALSE, cache=TRUE, eval=FALSE}
stan_any2013 <- run_stan(target_indication_table = target_indication_table_known_status, association_table = new_associations, MSH_similarity = average_similarity,  top_mesh =  mesh_properties, gene_table = gene_properties, pg = c(RVIS=2, Time=4), pe = 2, filter_list=list(any = function(x) {x}), sigmab=sigmab, mualpha=mualpha, sigmaalpha=sigmaalpha, save_file="../results/any_new.rds", cores=ncore)
```

```{r label=ModelFitPlotChunk, include=FALSE}
similarities <- seq(0, 1, 0.01)
prediction_df_gwas <- do.call(generate_prediction_df, c(stan_gwas, list(similarities=similarities))) %>% mutate(Analysis="Full Data", Source="GWAS")
prediction_df_omim <- do.call(generate_prediction_df, c(stan_omim, list(similarities=similarities))) %>% mutate(Analysis="Full Data", Source="OMIM")
prediction_df_del <- do.call(generate_prediction_df, c(stan_del, list(similarities=similarities))) %>% mutate(Analysis="Full Data", Source="GWAS High/Moderate Deleterious")
prediction_df_gwas2013 <- do.call(generate_prediction_df, c(stan_gwas_2013, list(similarities=similarities))) %>% mutate(Analysis="New Genetic", Source="GWAS")
prediction_df_omim2013 <- do.call(generate_prediction_df, c(stan_omim_2013, list(similarities=similarities))) %>% mutate(Analysis="New Genetic", Source="OMIM")
prediction_df_del2013 <- do.call(generate_prediction_df, c(stan_del_2013, list(similarities=similarities))) %>% mutate(Analysis="New Genetic", Source="GWAS High/Moderate Deleterious")

combined_model_fits <- rbind(prediction_df_gwas, prediction_df_omim, prediction_df_del, prediction_df_gwas2013, prediction_df_omim2013, prediction_df_del2013)

saveRDS(combined_model_fits, file = "../results/ORForFig2.rds")
```

```{r label=GeneratingInputForShinyApp, include=FALSE, cache=TRUE, eval=TRUE}
stan_res_list <- list(gwas = stan_gwas, omim = stan_omim, both = stan_both)
filter_list <- list(gwas_filter, OMIM_filter, function(x) {x})

indications <- unique(target_indication_table$MSH)
associated_genes <- unique(gene_trait_association_table$ensembl_id)

ngenes <- length(associated_genes)
# Split into chunks to avoid memory problems
ntasks <- 50
genes_per_task <- ceiling(ngenes / ntasks)
gene_df <- data.frame(gene_start = seq(1, ngenes, genes_per_task)) %>% mutate(gene_end = pmin(gene_start + (genes_per_task - 1), ngenes))
params <- cbind(bind_rows(rep(list(gene_df),3)), stan_res_ind = rep(1:3, each=nrow(gene_df)))

pred_res <- vector("list", nrow(params))

pb <- txtProgressBar(min = 0, max = nrow(params), style = 3)

for (i in 1:nrow(params)) {
  setTxtProgressBar(pb, i)
  pred_res[[i]] <- cbind(predict_gene_mesh(ensembl_ids = associated_genes[params$gene_start[i]:params$gene_end[i]], mesh_terms = indications, association_table = gene_trait_association_table, similarity = average_similarity, gene_table = gene_properties, top_mesh = mesh_properties, stan_res= stan_res_list[[params$stan_res_ind[i]]], default_time = 13903.5, conf = 0.95, cutoff=0.5), data.frame(Model=names(stan_res_list)[params$stan_res_ind[i]], stringsAsFactors = FALSE))
}

close(pb)

output_for_app <- bind_rows(pred_res) %>% filter(!is.na(OMIMSimilarity) | !is.na(GWASSimilarity))

saveRDS(output_for_app, file = "../results/ShinyAppPrecomputed.rds")
```

```{r label=GeneratingInputForShinyAppKnownTargets, include=FALSE, cache=TRUE, eval=TRUE}
target_genes <- unique(target_indication_table$ensembl_id)

ngenes <- length(target_genes)
# Split into chunks to avoid memory problems
ntasks <- 50
genes_per_task <- ceiling(ngenes / ntasks)
gene_df <- data.frame(gene_start = seq(1, ngenes, genes_per_task)) %>% mutate(gene_end = pmin(gene_start + (genes_per_task - 1), ngenes))
params <- cbind(bind_rows(rep(list(gene_df),3)), stan_res_ind = rep(1:3, each=nrow(gene_df)))

pred_res <- vector("list", nrow(params))

pb <- txtProgressBar(min = 0, max = nrow(params), style = 3)

for (i in 1:length(stan_res_list)) {
  pred_res[[i]] <- cbind(predict_gene_mesh(ensembl_ids = target_genes[params$gene_start[i]:params$gene_end[i]], mesh_terms = indications, association_table = gene_trait_association_table, similarity = average_similarity, gene_table = gene_properties, top_mesh = mesh_properties, stan_res= stan_res_list[[params$stan_res_ind[i]]], default_time = NA, conf = 0.95, cutoff=0.5), data.frame(Model=names(stan_res_list)[params$stan_res_ind[i]], stringsAsFactors = FALSE))
}

output_for_app <- bind_rows(pred_res) %>% filter(!is.na(OMIMSimilarity) | !is.na(GWASSimilarity))

saveRDS(output_for_app, file = "../results/ShinyAppPrecomputedKnownTargets.rds")
```
